import Link from 'next/link'

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <Link href="/" className="text-2xl font-bold text-brand-600">
            ComplaintAI
          </Link>
        </div>
      </header>
      
      <main className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Disclaimer</h1>
        
        <div className="prose prose-gray max-w-none">
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-8">
            <h2 className="text-xl font-semibold text-amber-800 mb-2 mt-0">Important Notice</h2>
            <p className="text-amber-700 mb-0">
              Please read this disclaimer carefully before using our service. By using ComplaintAI, 
              you acknowledge that you have read, understood, and agree to this disclaimer.
            </p>
          </div>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Not Legal Advice</h2>
            <p className="text-gray-700 mb-4">
              <strong>ComplaintAI does not provide legal advice.</strong> The documents and information 
              provided through our service are for general informational and educational purposes only.
            </p>
            <p className="text-gray-700 mb-4">
              Nothing on this website or in our generated documents should be construed as legal advice 
              or the creation of a solicitor-client relationship. The information provided may not 
              reflect the most current legal developments and may not be applicable to your specific 
              situation.
            </p>
            <p className="text-gray-700">
              If you need legal advice, please consult a qualified solicitor or legal professional.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Not a Claims Management Company</h2>
            <p className="text-gray-700 mb-4">
              ComplaintAI is a <strong>document preparation service</strong>, not a Claims Management 
              Company (CMC) as defined by the Financial Conduct Authority.
            </p>
            <p className="text-gray-700 mb-4">We do NOT:</p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>Provide advice on whether you have a valid claim</li>
              <li>Assess the merits or likelihood of success of your complaint</li>
              <li>Act on your behalf or represent you</li>
              <li>Submit complaints or correspondence for you</li>
              <li>Manage your complaint or case</li>
              <li>Negotiate with businesses or ombudsmen on your behalf</li>
              <li>Take any percentage of compensation you receive</li>
            </ul>
            <p className="text-gray-700">
              You are solely responsible for deciding whether to submit a complaint and for all 
              communications with businesses, the Financial Ombudsman Service, or any other party.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">No Guarantees</h2>
            <p className="text-gray-700 mb-4">
              <strong>We make no guarantees about the outcome of any complaint you submit.</strong>
            </p>
            <p className="text-gray-700 mb-4">
              The success of a complaint depends on many factors specific to your individual 
              circumstances, including (but not limited to):
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>The specific facts of your case</li>
              <li>The evidence you can provide</li>
              <li>The policies and practices of the business you are complaining about</li>
              <li>Current legal and regulatory interpretations</li>
              <li>The discretion of the Financial Ombudsman Service</li>
            </ul>
            <p className="text-gray-700">
              Past success rates of complaints in general do not indicate or guarantee the likelihood 
              of success for your individual complaint.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Document Review Required</h2>
            <p className="text-gray-700 mb-4">
              The complaint letters generated by our service are <strong>templates</strong> based on 
              the information you provide. You must:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>Review the generated document carefully before use</li>
              <li>Verify all facts, dates, and figures are correct</li>
              <li>Make any necessary amendments to reflect your specific circumstances</li>
              <li>Ensure the document accurately represents your complaint</li>
            </ul>
            <p className="text-gray-700">
              We are not responsible for errors resulting from incorrect information you provide or 
              from your failure to review and amend the generated document.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Information Accuracy</h2>
            <p className="text-gray-700 mb-4">
              While we strive to ensure our service reflects current regulations and best practices, 
              we cannot guarantee the accuracy, completeness, or timeliness of the information provided.
            </p>
            <p className="text-gray-700">
              Laws, regulations, and ombudsman approaches change over time. The information in our 
              system may not reflect the most recent changes or may not apply to your specific situation.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Limitation of Liability</h2>
            <p className="text-gray-700 mb-4">
              To the fullest extent permitted by applicable law, ComplaintAI and its owners, 
              employees, and affiliates shall not be liable for:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mb-4">
              <li>Any loss or damage arising from the use of our service or generated documents</li>
              <li>Any decision made or action taken based on our documents or information</li>
              <li>The outcome of any complaint, whether successful or unsuccessful</li>
              <li>Any indirect, incidental, special, consequential, or punitive damages</li>
              <li>Loss of profits, revenue, data, or business opportunities</li>
            </ul>
            <p className="text-gray-700">
              Our total liability for any claim relating to our service shall not exceed the amount 
              you paid for the service giving rise to the claim.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Third Party Services</h2>
            <p className="text-gray-700">
              Our service may contain links to third-party websites (such as the Financial Ombudsman 
              Service, FCA, or Citizens Advice). We are not responsible for the content, accuracy, 
              or practices of these external sites.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Your Responsibilities</h2>
            <p className="text-gray-700 mb-4">By using our service, you confirm that:</p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>You are at least 18 years of age</li>
              <li>The information you provide is accurate and complete to the best of your knowledge</li>
              <li>You understand this is a document preparation service, not legal advice</li>
              <li>You will review any generated document before use</li>
              <li>You take full responsibility for any complaint you submit</li>
              <li>You understand there is no guarantee of any particular outcome</li>
            </ul>
          </section>
          
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Free Alternatives</h2>
            <p className="text-gray-700 mb-4">
              You do not need to use a paid service to make a complaint. Free alternatives include:
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>Complaining directly to the business yourself</li>
              <li>Using the Financial Ombudsman Service (free to consumers)</li>
              <li>Using free template letters from Citizens Advice or Which?</li>
              <li>Seeking free legal advice if you qualify for legal aid</li>
            </ul>
          </section>
          
          <section className="bg-gray-100 rounded-xl p-6 mt-12">
            <h3 className="font-semibold text-gray-900 mb-2">Questions?</h3>
            <p className="text-gray-700 mb-0">
              If you have any questions about this disclaimer, please contact us at: 
              legal@complaintai.co.uk
            </p>
          </section>
        </div>
      </main>
      
      <footer className="bg-white border-t border-gray-200 mt-12">
        <div className="max-w-4xl mx-auto px-4 py-8 text-center text-sm text-gray-600">
          <Link href="/" className="hover:text-brand-600">Home</Link>
          {' • '}
          <Link href="/terms" className="hover:text-brand-600">Terms of Service</Link>
          {' • '}
          <Link href="/privacy" className="hover:text-brand-600">Privacy Policy</Link>
        </div>
      </footer>
    </div>
  )
}
